### ISSUE TITLE
Version 1.0.0 Crashing

### ISSUE THREAD

**Issue by lutzifer9** [litetex-oss/mcm-raid-restore#121]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/litetex-oss/mcm-raid-restore/issues) or [closed](https://github.com/litetex-oss/mcm-raid-restore/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.

### What is/are your question(s)?

Hi,
I have Version 1.0.0 (from Modrinth) installed on a 1.21.0 Server with the Fabric Launcher.
Everything works great until i kill a Raid Captain, then the server crashes.
Any advise on how to fix the problem?

Thanks

Btw i attached the crash report

"---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 2024-11-09 15:18:48
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'net.minecraft.class_1799 net.minecraft.class_3765.method_61558(net.minecraft.class_7871)'
	at knot//net.minecraft.class_3763.handler$zzb000$raid-restore$onDeath(class_3763.java:547)
	at knot//net.minecraft.class_3763.method_6078(class_3763.java:137)
	at knot//net.minecraft.class_1309.method_5643(class_1309.java:1252)
	at knot//net.minecraft.class_3763.method_5643(class_3763.java:269)
	at knot//net.minecraft.class_1657.method_7324(class_1657.java:1303)
	at knot//net.minecraft.class_3222.method_7324(class_3222.java:1743)
	at knot//net.minecraft.class_3244$1.method_34218(class_3244.java:1650)
	at knot//net.minecraft.class_2824$1.method_34213(class_2824.java:174)
	at knot//net.minecraft.class_2824.method_34209(class_2824.java:74)
	at knot//net.minecraft.class_3244.method_12062(class_3244.java:1610)
	at knot//net.minecraft.class_2824.method_12251(class_2824.java:61)
	at knot//net.minecraft.class_2824.method_11054(class_2824.java:15)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:27)
	at knot//net.minecraft.class_3738.run(class_3738.java:18)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:162)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864)
	at knot//net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:136)
	at knot//net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846)
	at knot//net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840)
	at knot//net.minecraft.class_1255.method_5383(class_1255.java:121)
	at knot//net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:814)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Linux (amd64) version 6.1.0-23-amd64
	Java Version: 21.0.4, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 903389432 bytes (861 MiB) / 2703228928 bytes (2578 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
	Identifier: Intel64 Family 6 Model 61 Stepping 4
	Microarchitecture: Broadwell (Client)
	Frequency (GHz): 2.20
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: HD Graphics 6000
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MiB): 256.00
	Graphics card #0 deviceId: 0x1626
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 3725.82
	Virtual memory used (MiB): 6569.85
	Swap memory total (MiB): 976.00
	Swap memory used (MiB): 3.25
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 839217.50, total: 898775.81
	Space in storage for workdir (MiB): available: 839217.50, total: 898775.81
	JVM Flags: 1 total; -Xmx4G
	Server Running: true
	Player Count: 1 / 20; [class_3222['nerdy999'/13, l='ServerLevel[world]', x=3087.30, y=103.00, z=1750.26]]
	Active Data Packs: vanilla
	Available Data Packs: bundle, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -2660247523717262346
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)"

**Comment by lutzifer9** [comment]
I got the newest version to work on a 1.21.2 server, just got to wait until Xaero's Worldmap comes out on 1.21.2
